name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Neovim
        uses: MunifTanjim/setup-neovim-action@v1

      - name: Run Tests
        run: |
          nvim --headless -c 'PlenaryBustedDirectory tests/ {minimal_init = "tests/minimal_init.lua"}' -c qa
